# Generated by Django 2.1.5 on 2019-04-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
