# Generated by Django 2.1.5 on 2019-04-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_partners_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelTable(
            name='partners',
            table='contact',
        ),
    ]
